import type { SxProps, Theme } from '@mui/material/styles'
import { colors, layout } from '@/design-system/tokens'

export const heroSectionStyles = {
  root: {
    position: 'relative',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    overflow: 'hidden',
    color: colors.common.white,
    pt: { xs: 12, md: 14 },
    pb: { xs: 10, md: 12 },
    backgroundColor: colors.surface.dark,
    backgroundImage: `
      radial-gradient(ellipse 70% 55% at 12% 8%, ${colors.lime[400]}2e 0%, transparent 58%),
      radial-gradient(ellipse 55% 45% at 88% 12%, ${colors.lime[500]}1f 0%, transparent 52%),
      radial-gradient(ellipse 95% 75% at 50% 48%, ${colors.lime[400]}33 0%, ${colors.lime[500]}14 32%, transparent 68%),
      radial-gradient(ellipse 60% 40% at 18% 70%, ${colors.lime[400]}18 0%, transparent 55%),
      linear-gradient(180deg, ${colors.ink[900]} 0%, ${colors.surface.dark} 45%, ${colors.ink[950]} 100%)
    `,
  },
  content: {
    position: 'relative',
    zIndex: 1,
    maxWidth: 860,
    mx: 'auto',
    textAlign: 'center',
    alignItems: 'center',
  },
  eyebrow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    color: colors.ink[300],
    fontSize: '0.8rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    mb: 2,
  },
  eyebrowDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    backgroundColor: colors.lime[400],
    boxShadow: `0 0 12px ${colors.lime[400]}`,
  },
  brandGlow: {
    color: colors.common.white,
    fontSize: { xs: '2.6rem', sm: '3.5rem', md: '4.5rem' },
    fontWeight: 600,
    lineHeight: 1.05,
    letterSpacing: '-0.03em',
    textShadow: `0 0 35px rgba(255,255,255,0.3), 0 0 70px ${colors.lime[400]}55, 0 0 110px ${colors.lime[500]}25`,
  },
  headlineSecondary: {
    color: colors.ink[100],
    fontSize: { xs: '1.35rem', md: '1.75rem' },
    fontWeight: 500,
    mt: 1.5,
    maxWidth: 640,
    mx: 'auto',
  },
  support: {
    color: colors.ink[300],
    maxWidth: 560,
    mx: 'auto',
    mt: 2,
  },
  features: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: { xs: 1.5, md: 2.5 },
    mt: 3,
  },
  feature: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    color: colors.ink[200],
    fontSize: '0.875rem',
  },
  featureIcon: {
    width: 6,
    height: 6,
    borderRadius: '50%',
    backgroundColor: colors.lime[400],
  },
  ctas: {
    mt: 4,
    display: 'flex',
    flexDirection: { xs: 'column', sm: 'row' },
    gap: 1.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryCta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1.25,
    pl: 2.5,
    pr: 1,
    py: 1,
    borderRadius: `${layout.radius.pill}px`,
    backgroundColor: colors.common.white,
    color: colors.ink[900],
    textDecoration: 'none',
    fontWeight: 700,
    fontSize: '0.95rem',
    transition: 'transform 160ms ease, background-color 160ms ease',
    '&:hover': {
      backgroundColor: colors.ink[100],
      transform: 'translateY(-2px)',
    },
  },
  primaryCtaIcon: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    backgroundColor: colors.lime[400],
    color: colors.ink[900],
    display: 'grid',
    placeItems: 'center',
    fontSize: 16,
    fontWeight: 700,
  },
  secondaryCta: {
    display: 'inline-flex',
    alignItems: 'center',
    px: 2.75,
    py: 1.35,
    borderRadius: `${layout.radius.pill}px`,
    border: '1px solid rgba(255,255,255,0.28)',
    color: colors.common.white,
    textDecoration: 'none',
    fontWeight: 600,
    fontSize: '0.95rem',
    backgroundColor: 'rgba(255,255,255,0.03)',
    '&:hover': {
      backgroundColor: 'rgba(255,255,255,0.08)',
    },
  },
  footerRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: { xs: 20, md: 28 },
    zIndex: 1,
    px: { xs: 2, md: 4 },
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  scrollHint: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 1,
    color: colors.ink[300],
    fontSize: '0.8rem',
    textDecoration: 'none',
  },
} as const satisfies Record<string, SxProps<Theme>>
