import type { SxProps, Theme } from '@mui/material/styles'
import { colors, layout } from '@/design-system/tokens'

export const floatingDecorStyles = {
  root: {
    position: 'absolute',
    inset: 0,
    overflow: 'hidden',
    pointerEvents: 'none',
    zIndex: 0,
    perspective: 1200,
  },
  glow: {
    position: 'absolute',
    top: '10%',
    left: '50%',
    width: { xs: 340, md: 720 },
    height: { xs: 340, md: 720 },
    transform: 'translateX(-50%)',
    borderRadius: '50%',
    background: `radial-gradient(circle, ${colors.lime[400]}44 0%, ${colors.lime[500]}1a 38%, transparent 72%)`,
    filter: 'blur(65px)',
  },
  secondaryGlow: {
    position: 'absolute',
    top: '30%',
    left: '20%',
    width: { xs: 220, md: 440 },
    height: { xs: 220, md: 440 },
    borderRadius: '50%',
    background: `radial-gradient(circle, ${colors.lime[400]}24 0%, transparent 68%)`,
    filter: 'blur(55px)',
  },
  item: {
    position: 'absolute',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    px: 1.3,
    py: 0.65,
    borderRadius: `${layout.radius.md}px`,
    border: '1px solid rgba(255,255,255,0.14)',
    color: 'rgba(255,255,255,0.6)',
    fontSize: { xs: '0.75rem', md: '0.9rem' },
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
    fontWeight: 500,
    letterSpacing: '0.04em',
    backgroundColor: 'rgba(255,255,255,0.03)',
    backdropFilter: 'blur(6px)',
    userSelect: 'none',
  },
  itemIcon: {
    fontSize: { xs: 16, md: 18 },
    opacity: 0.95,
  },
  itemLabel: {
    lineHeight: 1,
  },
  cubeWrapper: {
    position: 'absolute',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transformStyle: 'preserve-3d',
  },
  cube: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 0.35,
    width: { xs: 52, md: 68 },
    height: { xs: 52, md: 68 },
    borderRadius: '12px',
    border: `1.5px solid ${colors.lime[400]}88`,
    backgroundColor: 'rgba(8, 20, 10, 0.55)',
    backdropFilter: 'blur(8px)',
    boxShadow: `0 0 24px ${colors.lime[400]}33, inset 0 0 16px ${colors.lime[400]}22`,
    color: colors.lime[300],
    transformStyle: 'preserve-3d',
    '&::before': {
      content: '""',
      position: 'absolute',
      inset: -6,
      borderRadius: '16px',
      border: '1px dashed rgba(255,255,255,0.2)',
      pointerEvents: 'none',
    },
  },
  cubeIcon: {
    fontSize: { xs: 18, md: 22 },
  },
  cubeLabel: {
    fontSize: { xs: '0.55rem', md: '0.65rem' },
    fontWeight: 700,
    letterSpacing: '0.04em',
    lineHeight: 1,
    textTransform: 'uppercase',
  },
} as const satisfies Record<string, SxProps<Theme>>

