import type { SxProps, Theme } from '@mui/material/styles'
import { colors, layout } from '@/design-system/tokens'

export const navbarStyles = {
  root: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1200,
    px: { xs: 1.5, md: 2.5 },
    py: 1.5,
  },
  bar: {
    maxWidth: layout.maxWidth.wide,
    mx: 'auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: { xs: 1, md: 2 },
    px: { xs: 1.25, md: 1.5 },
    py: 1,
    borderRadius: `${layout.radius.pill}px`,
    backgroundColor: 'rgba(10, 10, 10, 0.55)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    backdropFilter: 'blur(20px) saturate(1.35)',
    WebkitBackdropFilter: 'blur(20px) saturate(1.35)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.28)',
    willChange: 'transform',
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 0.75,
    textDecoration: 'none',
    color: colors.common.white,
    flexShrink: 0,
  },
  brandMark: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: colors.lime[400],
    color: colors.ink[900],
    display: 'grid',
    placeItems: 'center',
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: '-0.04em',
    lineHeight: 1,
  },
  brandName: {
    fontWeight: 600,
    fontSize: '1rem',
    letterSpacing: '-0.02em',
    color: colors.common.white,
  },
  links: {
    display: { xs: 'none', md: 'flex' },
    alignItems: 'center',
    gap: 0.35,
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  link: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 0.75,
    px: 1.5,
    py: 0.85,
    borderRadius: `${layout.radius.pill}px`,
    color: 'rgba(255, 255, 255, 0.78)',
    textDecoration: 'none',
    fontSize: '0.875rem',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    transition: 'color 160ms ease, background-color 160ms ease',
    '&:hover': {
      color: colors.common.white,
      backgroundColor: 'rgba(255, 255, 255, 0.05)',
    },
  },
  linkActive: {
    color: colors.common.white,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  linkActiveDot: {
    width: 7,
    height: 7,
    borderRadius: '50%',
    backgroundColor: colors.lime[400],
    boxShadow: `0 0 10px ${colors.lime[400]}`,
    flexShrink: 0,
  },
  navOutline: {
    display: 'inline-flex',
    alignItems: 'center',
    px: 1.75,
    py: 0.75,
    ml: 0.5,
    borderRadius: `${layout.radius.pill}px`,
    border: '1px solid rgba(255, 255, 255, 0.35)',
    color: colors.common.white,
    textDecoration: 'none',
    fontSize: '0.875rem',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    transition: 'color 160ms ease, background-color 160ms ease, border-color 160ms ease',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
    },
  },
  navOutlineActive: {
    borderColor: colors.lime[400],
    backgroundColor: 'rgba(175, 252, 65, 0.1)',
    color: colors.common.white,
  },
  actions: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    flexShrink: 0,
  },
  language: {
    display: { xs: 'none', lg: 'inline-flex' },
    alignItems: 'center',
    gap: 0.75,
    px: 1.5,
    py: 0.85,
    borderRadius: `${layout.radius.pill}px`,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    color: colors.common.white,
    fontSize: '0.875rem',
    fontWeight: 500,
    border: 'none',
    cursor: 'default',
  },
  languageIcon: {
    fontSize: 16,
    opacity: 0.9,
  },
  languageChevron: {
    fontSize: 16,
    opacity: 0.7,
  },
  primaryCta: {
    display: { xs: 'none', sm: 'inline-flex' },
    alignItems: 'center',
    gap: 1.25,
    pl: 2,
    pr: 0.65,
    py: 0.55,
    borderRadius: `${layout.radius.pill}px`,
    backgroundColor: colors.common.white,
    color: colors.ink[900],
    textDecoration: 'none',
    fontSize: '0.875rem',
    fontWeight: 600,
    whiteSpace: 'nowrap',
    transition: 'transform 160ms ease, background-color 160ms ease',
    '&:hover': {
      backgroundColor: colors.ink[100],
      transform: 'translateY(-1px)',
    },
  },
  primaryCtaIcon: {
    width: 30,
    height: 30,
    borderRadius: '50%',
    backgroundColor: colors.lime[400],
    color: colors.ink[900],
    display: 'grid',
    placeItems: 'center',
    flexShrink: 0,
  },
  secondaryCta: {
    display: { xs: 'none', md: 'inline-flex' },
    alignItems: 'center',
    px: 1.85,
    py: 0.9,
    borderRadius: `${layout.radius.pill}px`,
    border: '1px solid rgba(255, 255, 255, 0.35)',
    color: colors.common.white,
    textDecoration: 'none',
    fontSize: '0.875rem',
    fontWeight: 500,
    whiteSpace: 'nowrap',
    '&:hover': {
      backgroundColor: 'rgba(255, 255, 255, 0.06)',
    },
  },
} as const satisfies Record<string, SxProps<Theme>>
